# Generated by Django 3.2 on 2021-10-08 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='coordinates_lat',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='coordinates_lng',
            new_name='lng',
        ),
    ]
