# Generated by Django 3.2 on 2021-10-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_alter_place_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='created_at',
        ),
        migrations.AddField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления координат'),
        ),
    ]
