# Generated by Django 3.2 on 2021-10-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_alter_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='processed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='обработан'),
        ),
    ]
