# Generated by Django 3.2 on 2021-10-07 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='processed',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('processed', 'Обработаный'), ('not_processed', 'Необработанный')], db_index=True, default='not_processed', max_length=13, verbose_name='Статус'),
        ),
    ]
