# Generated by Django 3.2 on 2021-10-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_auto_20211007_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.CharField(choices=[('cash', 'Наличными'), ('card', 'Картой'), ('not_selected', 'Не выбран')], default='not_selected', max_length=13, verbose_name='Оплата'),
        ),
    ]
