# Generated by Django 3.2 on 2021-10-07 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(null=True, related_name='orders', to='foodcartapp.Restaurant'),
        ),
    ]
