# Generated by Django 3.2 on 2021-10-15 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0057_alter_orderitem_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderRestaurant',
        ),
    ]
